# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-25 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bcost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='smobile',
            field=models.IntegerField(),
        ),
    ]
