# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-30 07:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190725_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='abc',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Publisher'),
        ),
    ]
